branches:
  except:
  - "/^wip/"
language: node_js
dist: bionic
addons:
  firefox: latest-esr
node_js:
- '10'
before_install:
- mkdir geckodriver/
- wget https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz
- tar xvf geckodriver-v0.22.0-linux64.tar.gz -C geckodriver/
- export PATH="`pwd`/cvc4:`pwd`/geckodriver:$PATH"
- sudo apt-get update -q -y
- sudo apt-get install -y pulseaudio graphicsmagick libpulse-dev libcanberra-dev libatlas-base-dev unzip
- pulseaudio --start
script:
- npm run lint
- LOCALE="en-US" TZ="America/Los_Angeles" npm test
after_success: npm run coverage
