branches:
  except:
  - "/^wip/"
language: node_js
dist: xenial
addons:
  firefox: latest-esr
node_js:
- '10'
before_install:
- mkdir cvc4/
- wget https://almond-static.stanford.edu/test-data/cvc4-1.6-x86_64-linux-opt -O cvc4/cvc4
- chmod +x cvc4/cvc4
- mkdir geckodriver/
- wget https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz
- tar xvf geckodriver-v0.22.0-linux64.tar.gz -C geckodriver/
- export PATH="`pwd`/cvc4:`pwd`/geckodriver:$PATH"
- sudo apt-get update -q -y
- sudo apt-get install -y graphicsmagick realpath python3 libpulse-dev pulseaudio
- pulseaudio --start
install:
- travis_retry yarn
- pyenv global 3.6.7
- pip3 install tensorflow
- pip3 install 'git+https://github.com/stanford-oval/mycroft-precise'
script:
- yarn lint
- TZ="America/Los_Angeles" yarn test
after_success: yarn run coverage
